Add pushit SFX
MichaelJolley/vulcan pull request #33
Opened 2020-03-05 21:19 UTC by vin-e

Adds push it by SnP sound effect. 

@MichaelJolley it is about 14 seconds and if you think this is too long I can clip if further.

2020-03-06 01:22 UTC, michaeljolley requested changes
I love this @vin-e.  Can we clip it to just "ooo push it, push it real good" so we don't get hit by the music police?

2020-03-06 03:10 UTC, vin-e commented
Yeah no problem. I will get it updated tomorrow.

2020-03-07 18:37 UTC, vin-e commented
@MichaelJolley the audio file has been updated to your approved version. 🍾

2020-03-07 19:15 UTC, michaeljolley approved these changes

2020-03-07 19:15 UTC, merged